package tn.edu.foodine.gui;

import tn.edu.foodine.entities.User;
import tn.edu.foodine.services.ServiceUtilisateur;
import java.sql.Date;
import java.time.format.DateTimeFormatter;
import java.util.Properties;
import javafx.collections.ObservableList;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class Mail {

    ServiceUtilisateur su = new ServiceUtilisateur();
    ObservableList<User> usersList;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MMMM");

    public void sendMail(String name, String desc, Date date_deb, Date date_fin) {
        // ----- MAIL -----
        String from = "foodine01@gmail.com";
        String host = "smtp.gmail.com";

        // Get system properties
        Properties properties = System.getProperties();

        // Setup mail server
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", "465");
        properties.put("mail.smtp.ssl.enable", "true");
        properties.put("mail.smtp.auth", "true");

        // Get the Session object.// and pass username and password
        Session session = Session.getInstance(properties, new javax.mail.Authenticator() {

            @Override
            protected PasswordAuthentication getPasswordAuthentication() {

                return new PasswordAuthentication(from, "foodinefoodine");

            }

        });

        usersList = su.getAll2();
        for (User user : usersList) {
            try {
                // Create a default MimeMessage object.
                MimeMessage message = new MimeMessage(session);

                // Set From: header field of the header.
                message.setFrom(new InternetAddress(from));

                // Set To: header field of the header.
                message.addRecipient(Message.RecipientType.TO, new InternetAddress(user.getEmail()));

                // Set Subject: header field
                message.setSubject("Foodine - Nouvel evénement!");

                // Now set the actual message
                message.setContent(
                        "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n"
                        + "<head>\n"
                        + "    <!--[if gte mso 9]>\n"
                        + "    <xml>\n"
                        + "        <o:OfficeDocumentSettings>\n"
                        + "            <o:AllowPNG/>\n"
                        + "            <o:PixelsPerInch>96</o:PixelsPerInch>\n"
                        + "        </o:OfficeDocumentSettings>\n"
                        + "    </xml>\n"
                        + "    <![endif]-->\n"
                        + "    <meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\n"
                        + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\" />\n"
                        + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n"
                        + "    <meta name=\"format-detection\" content=\"date=no\" />\n"
                        + "    <meta name=\"format-detection\" content=\"address=no\" />\n"
                        + "    <meta name=\"format-detection\" content=\"telephone=no\" />\n"
                        + "    <meta name=\"x-apple-disable-message-reformatting\" />\n"
                        + "    <!--[if !mso]><!-->\n"
                        + "    <link href=\"https://fonts.googleapis.com/css?family=Kreon:400,700|Playfair+Display:400,400i,700,700i|Raleway:400,400i,700,700i|Roboto:400,400i,700,700i\" rel=\"stylesheet\" />\n"
                        + "    <!--<![endif]-->\n"
                        + "    <title>Email Template</title>\n"
                        + "    <!--[if gte mso 9]>\n"
                        + "    <style type=\"text/css\" media=\"all\">\n"
                        + "        sup { font-size: 100% !important; }\n"
                        + "    </style>\n"
                        + "    <![endif]-->\n"
                        + "\n"
                        + "\n"
                        + "    <style type=\"text/css\" media=\"screen\">\n"
                        + "        /* Linked Styles */\n"
                        + "        body { padding:0 !important; margin:0 !important; display:block !important; min-width:100% !important; width:100% !important; background:#1e52bd; -webkit-text-size-adjust:none }\n"
                        + "        a { color:#000001; text-decoration:none }\n"
                        + "        p { padding:0 !important; margin:0 !important }\n"
                        + "        img { -ms-interpolation-mode: bicubic; /* Allow smoother rendering of resized image in Internet Explorer */ }\n"
                        + "        .mcnPreviewText { display: none !important; }\n"
                        + "        .text-footer2 a { color: #ffffff; }\n"
                        + "\n"
                        + "        /* Mobile styles */\n"
                        + "        @media only screen and (max-device-width: 480px), only screen and (max-width: 480px) {\n"
                        + "            .mobile-shell { width: 100% !important; min-width: 100% !important; }\n"
                        + "\n"
                        + "            .m-center { text-align: center !important; }\n"
                        + "            .m-left { text-align: left !important; margin-right: auto !important; }\n"
                        + "\n"
                        + "            .center { margin: 0 auto !important; }\n"
                        + "            .content2 { padding: 8px 15px 12px !important; }\n"
                        + "            .t-left { float: left !important; margin-right: 30px !important; }\n"
                        + "            .t-left-2  { float: left !important; }\n"
                        + "\n"
                        + "            .td { width: 100% !important; min-width: 100% !important; }\n"
                        + "\n"
                        + "            .content { padding: 30px 15px !important; }\n"
                        + "            .section { padding: 30px 15px 0px !important; }\n"
                        + "\n"
                        + "            .m-br-15 { height: 15px !important; }\n"
                        + "            .mpb5 { padding-bottom: 5px !important; }\n"
                        + "            .mpb15 { padding-bottom: 15px !important; }\n"
                        + "            .mpb20 { padding-bottom: 20px !important; }\n"
                        + "            .mpb30 { padding-bottom: 30px !important; }\n"
                        + "            .m-padder { padding: 0px 15px !important; }\n"
                        + "            .m-padder2 { padding-left: 15px !important; padding-right: 15px !important; }\n"
                        + "            .p70 { padding: 30px 0px !important; }\n"
                        + "            .pt70 { padding-top: 30px !important; }\n"
                        + "            .p0-15 { padding: 0px 15px !important; }\n"
                        + "            .p30-15 { padding: 30px 15px !important; }\n"
                        + "            .p30-15-0 { padding: 30px 15px 0px 15px !important; }\n"
                        + "            .p0-15-30 { padding: 0px 15px 30px 15px !important; }\n"
                        + "\n"
                        + "\n"
                        + "            .text-footer { text-align: center !important; }\n"
                        + "\n"
                        + "            .m-td,\n"
                        + "            .m-hide { display: none !important; width: 0 !important; height: 0 !important; font-size: 0 !important; line-height: 0 !important; min-height: 0 !important; }\n"
                        + "\n"
                        + "            .m-block { display: block !important; }\n"
                        + "\n"
                        + "            .fluid-img img { width: 100% !important; max-width: 100% !important; height: auto !important; }\n"
                        + "\n"
                        + "            .column,\n"
                        + "            .column-dir,\n"
                        + "            .column-top,\n"
                        + "            .column-empty,\n"
                        + "            .column-top-30,\n"
                        + "            .column-top-60,\n"
                        + "            .column-empty2,\n"
                        + "            .column-bottom { float: left !important; width: 100% !important; display: block !important; }\n"
                        + "\n"
                        + "            .column-empty { padding-bottom: 15px !important; }\n"
                        + "            .column-empty2 { padding-bottom: 30px !important; }\n"
                        + "\n"
                        + "            .content-spacing { width: 15px !important; }\n"
                        + "        }\n"
                        + "    </style>\n"
                        + "</head>\n"
                        + "<body class=\"body\"style=\"padding:0 !important; margin:0 !important; display:block !important; min-width:100% !important; width:100% !important; background:#1e52bd; -webkit-text-size-adjust:none;\">\n"
                        + "<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#1e52bd\">\n"
                        + "    <tr>\n"
                        + "        <td align=\"center\" valign=\"top\">\n"
                        + "            <!-- Main -->\n"
                        + "            <table width=\"650\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"mobile-shell\">\n"
                        + "                <tr>\n"
                        + "                    <td class=\"td\" style=\"width:650px; min-width:650px; font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal;\">\n"
                        + "                        <!-- Header -->\n"
                        + "                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "\n"
                        + "                            <!-- END Top bar -->\n"
                        + "                            <!-- Logo -->\n"
                        + "                            <tr>\n"
                        + "                                <td bgcolor=\"#ffffff\" class=\"p30-15 img-center\" style=\"padding: 30px; border-radius: 20px 20px 0px 0px; font-size:0pt; line-height:0pt; text-align:center;\"><a href=\"#\" target=\"_blank\"><img src=\"https://i.ibb.co/nLxpyC3/logoo.png\" width=\"244\" height=\"75\" border=\"0\" alt=\"\" /></a></td>\n"
                        + "                            </tr>\n"
                        + "                            <!-- END Logo -->\n"
                        + "                            <!-- Nav -->\n"
                        + "                            <!-- END Nav -->\n"
                        + "                        </table>\n"
                        + "                        <!-- END Header -->\n"
                        + "\n"
                        + "                        <!-- Section 1 -->\n"
                        + "                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ebebeb\">\n"
                        + "                            <tr>\n"
                        + "                                <td class=\"fluid-img\"style=\"font-size:0pt; line-height:0pt; text-align:left;\"><img src=\"https://i.ibb.co/VqTDJc3/banner-2.png\" width=\"650\" height=\"358\" border=\"0\" alt=\"\" /></td>\n"
                        + "                            </tr>\n"
                        + "                            <tr>\n"
                        + "                                <td class=\"p30-15-0\" style=\"padding: 50px 30px 0px;\" bgcolor=\"#ffffff\">\n"
                        + "                                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "\n"
                        + "                                        <tr>\n"
                        + "                                            <td class=\"h2-center\"style=\"color:#000000; font-family:'Playfair Display', Times, 'Times New Roman', serif; font-size:32px; line-height:36px; text-align:center; padding-bottom:20px;\">Ne ratez pas le nouvel evenement !</td>\n"
                        + "                                        </tr>\n"
                        + "\n"
                        + "                                        <tr>\n"
                        + "                                            <td class=\"h2-center\"style=\"color:#000000; font-family:'Playfair Display', Times, 'Times New Roman', serif; font-size:48px;font-weight: bold; text-transform: uppercase; line-height:36px; text-align:center; padding-bottom:20px;\">" + name + "</td>\n"
                        + "                                        </tr>\n"
                        + "                                        <tr>\n"
                        + "                                            <td class=\"h2-center\"style=\"color:#000000; font-family:'Playfair Display', Times, 'Times New Roman', serif; font-size:26px; line-height:24px; text-align:center; padding-bottom:20px;\">\n"
                        + "                                            Du " + date_deb.toLocalDate().format(formatter).toUpperCase() + " au " + date_fin.toLocalDate().format(formatter).toUpperCase() + "\n"
                        + "                                            </td>\n"
                        + "                                        </tr>\n"
                        + "                                        <tr>\n"
                        + "                                            <td class=\"text-center\"style=\"color:#5d5c5c; font-family:'Raleway', Arial,sans-serif; font-size:14px; line-height:22px; text-align:center; padding-bottom:22px;\">" + desc + "</td>\n"
                        + "                                        </tr>\n"
                        + "                                        <tr>\n"
                        + "                                            <td align=\"center\">\n"
                        + "                                                <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                                    <tr>\n"
                        + "                                                        <td class=\"text-button-orange\"style=\"background:#e85711; color:#ffffff; font-family:'Kreon', 'Times New Roman', Georgia, serif; font-size:14px; line-height:18px; text-align:center; padding:10px 30px; border-radius:20px;\"><a href=\"localhost:8000\" target=\"_blank\" class=\"link-white\"style=\"color:#ffffff; text-decoration:none;\"><span class=\"link-white\"style=\"color:#ffffff; text-decoration:none;\">Voir plus</span></a></td>\n"
                        + "                                                    </tr>\n"
                        + "                                                </table>\n"
                        + "                                            </td>\n"
                        + "                                        </tr>\n"
                        + "                                    </table>\n"
                        + "                                </td>\n"
                        + "                            </tr>\n"
                        + "                        </table>\n"
                        + "                        <!-- END Section 1 -->\n"
                        + "\n"
                        + "                        <!-- Section 2 -->\n"
                        + "                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                            <tr>\n"
                        + "                                <td>\n"
                        + "                                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#dde8fd\">\n"
                        + "                                        <tr>\n"
                        + "                                            <td class=\"fluid-img\"style=\"font-size:0pt; line-height:0pt; text-align:left;\"><img src=\"https://i.ibb.co/Kb7RcX8/free-white-blue.jpg\" width=\"650\" height=\"162\" border=\"0\" alt=\"\" /></td>\n"
                        + "                                        </tr>\n"
                        + "                                        <tr>\n"
                        + "                                            <td class=\"p0-15\" style=\"padding: 0px 30px;\">\n"
                        + "                                                <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                                    <tr>\n"
                        + "                                                        <td class=\"h2-center\"style=\"color:#000000; font-family:'Playfair Display', Times, 'Times New Roman', serif; font-size:32px; line-height:36px; text-align:center; padding-bottom:20px;\"><multiline>Evenements prochains</multiline></td>\n"
                        + "                                                    </tr>\n"
                        + "                                                    <tr>\n"
                        + "                                                        <td class=\"pb40\"style=\"padding-bottom:40px;\">\n"
                        + "                                                            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                                                <tr>\n"
                        + "                                                                    <td class=\"event-separator\"style=\"padding-bottom:40px; border-bottom:1px solid #ffffff;\">\n"
                        + "                                                                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                                                            <tr>\n"
                        + "                                                                                <th class=\"column-top\" width=\"60\"style=\"font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; vertical-align:top;\">\n"
                        + "                                                                                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                                                                        <tr>\n"
                        + "                                                                                            <td class=\"date\"style=\"color:#000000; font-family:'Raleway', Arial,sans-serif; font-size:12px; line-height:16px; text-align:left; padding-bottom:6px;\"><multiline>Mars</multiline></td>\n"
                        + "                                                                                        </tr>\n"
                        + "                                                                                        <tr>\n"
                        + "                                                                                            <td class=\"day\"style=\"color:#1e52bd; font-family:'Raleway', Arial,sans-serif; font-size:40px; line-height:44px; text-align:left; font-weight:bold;\"><multiline>15</multiline></td>\n"
                        + "                                                                                        </tr>\n"
                        + "                                                                                    </table>\n"
                        + "                                                                                </th>\n"
                        + "                                                                                <th class=\"column-empty\" width=\"10\"style=\"font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; direction:ltr;\"></th>\n"
                        + "                                                                                <th class=\"column-top\"style=\"font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; vertical-align:top;\">\n"
                        + "                                                                                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                                                                        <tr>\n"
                        + "                                                                                            <td class=\"h5-black black\"style=\"font-family:'Raleway', Arial,sans-serif; font-size:14px; line-height:18px; text-align:left; padding-bottom:15px; text-transform:uppercase; font-weight:bold; color:#000000;\"><multiline>Evenement 1</multiline></td>\n"
                        + "                                                                                        </tr>\n"
                        + "                                                                                        <tr>\n"
                        + "                                                                                            <td class=\"text black\"style=\"font-family:'Raleway', Arial,sans-serif; font-size:14px; line-height:22px; text-align:left; color:#000000;\"><multiline>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempo dolore setr tempore alipsinung.</multiline></td>\n"
                        + "                                                                                        </tr>\n"
                        + "                                                                                    </table>\n"
                        + "                                                                                </th>\n"
                        + "                                                                                <th class=\"column-empty\" width=\"10\"style=\"font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; direction:ltr;\"></th>\n"
                        + "                                                                                <th class=\"column-top\" width=\"156\"style=\"font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; vertical-align:top;\">\n"
                        + "                                                                                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                                                                        <tr>\n"
                        + "                                                                                            <td align=\"right\">\n"
                        + "                                                                                                <table class=\"m-left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                                                                                    <tr>\n"
                        + "                                                                                                        <td class=\"text-button button-blue\"style=\"font-family:'Kreon', Georgia, serif; font-size:14px; line-height:18px; text-align:center; padding:10px 30px; border-radius:20px; background:transparent; color:#1e52bd; border:1px solid #1e52bd;\"><multiline><a href=\"localhost:8000/evenements\" target=\"_blank\" class=\"link-blue\"style=\"color:#1e52bd; text-decoration:none;\"><span class=\"link-blue\"style=\"color:#1e52bd; text-decoration:none;\">Voir plus</span></a></multiline></td>\n"
                        + "                                                                                                    </tr>\n"
                        + "                                                                                                </table>\n"
                        + "                                                                                            </td>\n"
                        + "                                                                                        </tr>\n"
                        + "                                                                                    </table>\n"
                        + "                                                                                </th>\n"
                        + "                                                                            </tr>\n"
                        + "                                                                        </table>\n"
                        + "                                                                    </td>\n"
                        + "                                                                </tr>\n"
                        + "                                                            </table>\n"
                        + "                                                        </td>\n"
                        + "                                                    </tr>\n"
                        + "                                                    <tr>\n"
                        + "                                                        <td class=\"pb40\"style=\"padding-bottom:40px;\">\n"
                        + "                                                            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                                                <tr>\n"
                        + "                                                                    <th class=\"column-top\" width=\"60\"style=\"font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; vertical-align:top;\">\n"
                        + "                                                                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                                                            <tr>\n"
                        + "                                                                                <td class=\"date\"style=\"color:#000000; font-family:'Raleway', Arial,sans-serif; font-size:12px; line-height:16px; text-align:left; padding-bottom:6px;\"><multiline>Mars</multiline></td>\n"
                        + "                                                                            </tr>\n"
                        + "                                                                            <tr>\n"
                        + "                                                                                <td class=\"day\"style=\"color:#1e52bd; font-family:'Raleway', Arial,sans-serif; font-size:40px; line-height:44px; text-align:left; font-weight:bold;\"><multiline>21</multiline></td>\n"
                        + "                                                                            </tr>\n"
                        + "                                                                        </table>\n"
                        + "                                                                    </th>\n"
                        + "                                                                    <th class=\"column-empty\" width=\"10\"style=\"font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; direction:ltr;\"></th>\n"
                        + "                                                                    <th class=\"column-top\"style=\"font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; vertical-align:top;\">\n"
                        + "                                                                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                                                            <tr>\n"
                        + "                                                                                <td class=\"h5-black black\"style=\"font-family:'Raleway', Arial,sans-serif; font-size:14px; line-height:18px; text-align:left; padding-bottom:15px; text-transform:uppercase; font-weight:bold; color:#000000;\"><multiline>Evenement 2</multiline></td>\n"
                        + "                                                                            </tr>\n"
                        + "                                                                            <tr>\n"
                        + "                                                                                <td class=\"text black\"style=\"font-family:'Raleway', Arial,sans-serif; font-size:14px; line-height:22px; text-align:left; color:#000000;\"><multiline>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempo dolore setr tempore alipsinung.</multiline></td>\n"
                        + "                                                                            </tr>\n"
                        + "                                                                        </table>\n"
                        + "                                                                    </th>\n"
                        + "                                                                    <th class=\"column-empty\" width=\"10\"style=\"font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; direction:ltr;\"></th>\n"
                        + "                                                                    <th class=\"column-top\" width=\"156\"style=\"font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; vertical-align:top;\">\n"
                        + "                                                                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                                                            <tr>\n"
                        + "                                                                                <td align=\"right\">\n"
                        + "                                                                                    <table class=\"m-left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                                                                        <tr>\n"
                        + "                                                                                            <td class=\"text-button button-blue\"style=\"font-family:'Kreon', Georgia, serif; font-size:14px; line-height:18px; text-align:center; padding:10px 30px; border-radius:20px; background:transparent; color:#1e52bd; border:1px solid #1e52bd;\"><multiline><a href=\"#\" target=\"_blank\" class=\"link-blue\"style=\"color:#1e52bd; text-decoration:none;\"><span class=\"link-blue\"style=\"color:#1e52bd; text-decoration:none;\">Voir plus</span></a></multiline></td>\n"
                        + "                                                                                        </tr>\n"
                        + "                                                                                    </table>\n"
                        + "                                                                                </td>\n"
                        + "                                                                            </tr>\n"
                        + "                                                                        </table>\n"
                        + "                                                                    </th>\n"
                        + "                                                                </tr>\n"
                        + "                                                            </table>\n"
                        + "                                                        </td>\n"
                        + "                                                    </tr>\n"
                        + "                                                    <tr>\n"
                        + "                                                        <td align=\"center\">\n"
                        + "                                                            <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                                                <tr>\n"
                        + "                                                                    <td class=\"text-button button-blue2\"style=\"font-family:'Kreon', Georgia, serif; font-size:14px; line-height:18px; text-align:center; padding:10px 30px; border-radius:20px; background:#1e52bd; color:#ffffff;\"><multiline><a href=\"#\" target=\"_blank\" class=\"link-white\"style=\"color:#ffffff; text-decoration:none;\"><span class=\"link-white\"style=\"color:#ffffff; text-decoration:none;\">Voir tous les evenements</span></a></multiline></td>\n"
                        + "                                                                </tr>\n"
                        + "                                                            </table>\n"
                        + "                                                        </td>\n"
                        + "                                                    </tr>\n"
                        + "                                                </table>\n"
                        + "                                            </td>\n"
                        + "                                        </tr>\n"
                        + "                                        <tr>\n"
                        + "                                            <td class=\"fluid-img\"style=\"font-size:0pt; line-height:0pt; text-align:left;\"><img src=\"https://i.ibb.co/Wkrd2bT/free-blue-white.jpg\" width=\"650\" height=\"160\" border=\"0\" alt=\"\" /></td>\n"
                        + "                                        </tr>\n"
                        + "                                    </table>\n"
                        + "                                </td>\n"
                        + "                            </tr>\n"
                        + "\n"
                        + "                        </table>\n"
                        + "                        <!-- END Section 2 -->\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "                        <!-- Footer -->\n"
                        + "                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                            <tr>\n"
                        + "                                <td class=\"p30-15-0\" bgcolor=\"#ffffff\" style=\"border-radius: 0px 0px 20px 20px; padding: 70px 30px 0px 30px;\">\n"
                        + "                                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                        <tr>\n"
                        + "                                            <td align=\"center\" class=\"p30-15\" style=\"border-top: 1px solid #ebebeb; padding: 30px;\">\n"
                        + "                                                <table class=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"style=\"text-align:center;\">\n"
                        + "                                                    <tr>\n"
                        + "                                                        <th class=\"column-top\" width=\"180\"style=\"font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; vertical-align:top;\">\n"
                        + "                                                            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                                                <tr>\n"
                        + "                                                                    <td class=\"text-footer\"style=\"color:#5d5c5c; font-family:'Raleway', Arial,sans-serif; font-size:13px; line-height:22px; text-align:left;\">\n"
                        + "                                                                        <multiline>\n"
                        + "                                                                            <strong>Catalog &amp; Brochures</strong><br />\n"
                        + "                                                                            <a href=\"#\" target=\"_blank\" class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\"><span class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\">Request</span></a> <br />\n"
                        + "                                                                            <a href=\"#\" target=\"_blank\" class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\"><span class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\">View Online</span></a> <br />\n"
                        + "                                                                            <a href=\"#\" target=\"_blank\" class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\"><span class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\">Buying Guides</span></a>\n"
                        + "                                                                        </multiline>\n"
                        + "                                                                    </td>\n"
                        + "                                                                </tr>\n"
                        + "                                                            </table>\n"
                        + "                                                        </th>\n"
                        + "                                                        <th class=\"column-empty\" width=\"20\"style=\"font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; direction:ltr;\"></th>\n"
                        + "                                                        <th class=\"column-top\" width=\"180\"style=\"font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; vertical-align:top;\">\n"
                        + "                                                            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                                                <tr>\n"
                        + "                                                                    <td class=\"text-footer\"style=\"color:#5d5c5c; font-family:'Raleway', Arial,sans-serif; font-size:13px; line-height:22px; text-align:left;\">\n"
                        + "                                                                        <multiline>\n"
                        + "                                                                            <strong>Need Help</strong><br />\n"
                        + "                                                                            <a href=\"#\" target=\"_blank\" class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\"><span class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\">FAQ</span></a><br />\n"
                        + "                                                                            <a href=\"#\" target=\"_blank\" class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\"><span class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\">Contact Us</span></a><br />\n"
                        + "                                                                            <a href=\"#\" target=\"_blank\" class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\"><span class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\">Return Policy</span></a><br />\n"
                        + "                                                                            <a href=\"#\" target=\"_blank\" class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\"><span class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\">Children's Product Registration</span></a>\n"
                        + "                                                                        </multiline>\n"
                        + "                                                                    </td>\n"
                        + "                                                                </tr>\n"
                        + "                                                            </table>\n"
                        + "                                                        </th>\n"
                        + "                                                        <th class=\"column-empty\" width=\"20\"style=\"font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; direction:ltr;\"></th>\n"
                        + "                                                        <th class=\"column-top\" width=\"180\"style=\"font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; vertical-align:top;\">\n"
                        + "                                                            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
                        + "                                                                <tr>\n"
                        + "                                                                    <td class=\"text-footer\"style=\"color:#5d5c5c; font-family:'Raleway', Arial,sans-serif; font-size:13px; line-height:22px; text-align:left;\">\n"
                        + "                                                                        <multiline>\n"
                        + "                                                                            <strong>Delivery Information</strong><br />\n"
                        + "                                                                            <a href=\"#\" target=\"_blank\" class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\"><span class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\">Store Delivery</span></a> <br />\n"
                        + "                                                                            <a href=\"#\" target=\"_blank\" class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\"><span class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\">Online Delivery</span></a> <br />\n"
                        + "                                                                            <a href=\"#\" target=\"_blank\" class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\"><span class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\">Picking with Delivery</span></a> <br />\n"
                        + "                                                                            <a href=\"#\" target=\"_blank\" class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\"><span class=\"link-grey\"style=\"color:#5d5c5c; text-decoration:none;\">Track an Order</span></a>\n"
                        + "                                                                        </multiline>\n"
                        + "                                                                    </td>\n"
                        + "                                                                </tr>\n"
                        + "                                                            </table>\n"
                        + "                                                        </th>\n"
                        + "                                                    </tr>\n"
                        + "                                                </table>\n"
                        + "                                            </td>\n"
                        + "                                        </tr>\n"
                        + "                                    </table>\n"
                        + "                                </td>\n"
                        + "                            </tr>\n"
                        + "                        </table>\n"
                        + "\n"
                        + "                        <!-- END Footer -->\n"
                        + "                    </td>\n"
                        + "                </tr>\n"
                        + "            </table>\n"
                        + "            <!-- END Main -->\n"
                        + "\n"
                        + "        </td>\n"
                        + "    </tr>\n"
                        + "</table>\n"
                        + "</body>\n"
                        + "</html>",
                        "text/html");

                System.out.println("sending...");
                // Send message
                Transport.send(message);
                System.out.println("Sent message successfully....");
            } catch (MessagingException mex) {
            }
        }
    }
}
